export interface OrderHall {
  id: string;
  name: string;
  /** In-app hall place label (not a Discord channel). */
  hallLabel: string;
  tiedTo: string;
  mapPlace: string;
  /** From DESIGN_ORDER_HALLS_MAP.md — hub/city attach vs standalone landmark. */
  placement: "hub" | "city" | "standalone";
  /** Map region id this hall pins to (canon places only). */
  regionId: string;
  glyph: string;
}

/** Locked Creed 2026-09-22 / map pins 2026-09-25. Do not invent locations. */
export const ORDER_HALLS: OrderHall[] = [
  {
    id: "dawns-chapel",
    name: "Dawn's Chapel",
    hallLabel: "Hall · Dawn's Chapel",
    tiedTo: "Priest",
    mapPlace: "Virelios (faith quarter)",
    placement: "hub",
    regionId: "virelios",
    glyph: "✝",
  },
  {
    id: "crusaders-hall",
    name: "Crusaders' Hall",
    hallLabel: "Hall · Crusaders' Hall",
    tiedTo: "Paladin",
    mapPlace: "War Colleges region — own hall",
    placement: "standalone",
    regionId: "war-colleges",
    glyph: "⚔",
  },
  {
    id: "hall-of-the-elements",
    name: "Hall of the Elements",
    hallLabel: "Hall · Hall of the Elements",
    tiedTo: "Shaman",
    mapPlace: "High Mountains — peak shrine",
    placement: "standalone",
    regionId: "high-mountains",
    glyph: "☽",
  },
  {
    id: "thieves-hall",
    name: "Thieves' Hall",
    hallLabel: "Hall · Thieves' Hall",
    tiedTo: "Rogue",
    mapPlace: "The Undercity (Virelios)",
    placement: "hub",
    regionId: "virelios",
    glyph: "◉",
  },
  {
    id: "the-mead-halls",
    name: "The Mead Halls",
    hallLabel: "Hall · The Mead Halls",
    tiedTo: "Warrior",
    mapPlace: "War Colleges region — feast campus",
    placement: "standalone",
    regionId: "war-colleges",
    glyph: "⚒",
  },
  {
    id: "the-arcane-academy",
    name: "The Arcane Academy",
    hallLabel: "Hall · The Arcane Academy",
    tiedTo: "Mage",
    mapPlace: "Virelios (near Bardwook)",
    placement: "hub",
    regionId: "virelios",
    glyph: "✦",
  },
  {
    id: "the-secret-wilds",
    name: "The Secret Wilds",
    hallLabel: "Hall · The Secret Wilds",
    tiedTo: "Druid",
    mapPlace: "Deep Grove — own wilds",
    placement: "standalone",
    regionId: "grove",
    glyph: "❧",
  },
  {
    id: "bell-hall-ruins",
    name: "Bell Hall Ruins",
    hallLabel: "Hall · Bell Hall Ruins",
    tiedTo: "Warlock",
    mapPlace: "The Wastes — own ruin",
    placement: "standalone",
    regionId: "wastes",
    glyph: "◎",
  },
  {
    id: "the-sacred-crypts",
    name: "The Sacred Crypts",
    hallLabel: "Hall · The Sacred Crypts",
    tiedTo: "Necromancer",
    mapPlace: "Stone Halls mountains — crypt campus",
    placement: "standalone",
    regionId: "stone-halls",
    glyph: "†",
  },
  {
    id: "golem-university",
    name: "Golem University",
    hallLabel: "Hall · Golem University",
    tiedTo: "Golemancer",
    mapPlace: "Stone Halls region — craft campus",
    placement: "standalone",
    regionId: "stone-halls",
    glyph: "⬡",
  },
  {
    id: "the-bellsong-auditorium",
    name: "The Bellsong Auditorium",
    hallLabel: "Hall · The Bellsong Auditorium",
    tiedTo: "Bard",
    mapPlace: "Virelios (Market/Pub)",
    placement: "hub",
    regionId: "virelios",
    glyph: "♪",
  },
  {
    id: "the-wolfclad-lodge",
    name: "The Wolfclad Lodge",
    hallLabel: "Hall · The Wolfclad Lodge",
    tiedTo: "Hunter",
    mapPlace: "Velkrath Wood — lodge clearing",
    placement: "standalone",
    regionId: "velkrath",
    glyph: "◷",
  },
  {
    id: "steamwhistle-college",
    name: "Steamwhistle College",
    hallLabel: "Hall · Steamwhistle College",
    tiedTo: "Tinker",
    mapPlace: "Cassanova",
    placement: "city",
    regionId: "cassanova",
    glyph: "⚙",
  },
  {
    id: "the-monastery-of-the-fist",
    name: "The Monastery of the Fist",
    hallLabel: "Hall · The Monastery of the Fist",
    tiedTo: "Monk",
    mapPlace: "Southern Isles — own monastery",
    placement: "standalone",
    regionId: "southern-isles",
    glyph: "☰",
  },
  {
    id: "the-blood-hideaway",
    name: "The Blood Hideaway",
    hallLabel: "Hall · The Blood Hideaway",
    tiedTo: "Vampires (affliction)",
    mapPlace: "Luminara Noctis — night district",
    placement: "city",
    regionId: "starveil",
    glyph: "🩸",
  },
];
